### ISSUE TITLE
Rellenar tabla dummys players

### ISSUE THREAD

**Issue by PaulaMorBla14** [PaulaMorBla14/TFG-Baloncesto#10]
https://github.com/PaulaMorBla14/TFG-Baloncesto/blob/c90155ab8fb95613b4e63a40a92da7982e105bb2/TOY_1.Rmd#L149

Necesito rellenar cada columna con 0 o 1 (o T o F) dependiendo si aparece o no en la columna de `Merged_players`. Ahora mismo me esta rellenando todas las columnas de jugadores con solo el output de _LP1_, no me cambia a _LP2, LP3_... 

¿Qué debo cambiar?

En el PDF podréis ver lo que me debería de dar y la tabla final que me da. 

https://github.com/PaulaMorBla14/TFG-Baloncesto/blob/c90155ab8fb95613b4e63a40a92da7982e105bb2/TOY_1.pdf

**Comment by solmos** [comment]
El error es que le estás pasando un vector de longitud mayor a 1 al argumento pattern de la función `grepl()` y como te indica el mensaje de advertencia solo se utiliza el primer elemento de este.

```
> grepl(vec_players, df_DummyPlayers$Merged_Players, fixed=TRUE) 
[1]  TRUE FALSE FALSE FALSE  TRUE  TRUE  TRUE
Warning message:
In grepl(vec_players, df_DummyPlayers$Merged_Players, fixed = TRUE) :
  argument 'pattern' has length > 1 and only the first element will be used
```

Presta especial atención al tipo de objeto que aceptan los argumentos de las funciones (en este caso mira `?grepl`).

**Comment by solmos** [comment]
Por lo tanto debes evaluar esa misma expresión pero para cada elemento de `vec_players`. Te sugiero que utilices `sapply()` para esto.

**Comment by PaulaMorBla14** [comment]
De momento me he decantado por la función `dummy_cols` de` FastDummies` y parece funcionar bien. En la reunión lo podemos mirar si os parece bien como queda.
