### ISSUE TITLE
Agrupar por stints

### ISSUE THREAD

**Issue by solmos** [PaulaMorBla14/TFG-Baloncesto#12]
Veo que lo que haces aquí es quedarte con la úlitma fila de cada stint. Sin embargo, lo que deberías hacer más bien es agrupar por stint para luego calcular el más menos en cada stint.

https://github.com/PaulaMorBla14/TFG-Baloncesto/blob/ee06823af3a20b6384bec1ed536dca1f13eb6edb/TOY_1.Rmd#L119-L126

Date cuenta que de la forma que lo has hecho no obtienes el más menos de cada stint. El más menos de cada stint es la diferencia de puntos anotados *en ese stint*.

Por ejemplo, fíjate en el stint 3 de tu data frame `STINTS`:

```
> STINTS
     stint ID_Stint Merged_SG id_play points_L points_A PM          Merged_Players TF_Cambios
1       NC        1  S2017_G1       4        2        2  0 LP3_LP2_LP1_AP3_AP2_AP1         NC
2       NC        2  S2017_G1       7        5        7 -2 LP6_LP3_LP2_AP3_AP2_AP1         NC
3        C        3  S2017_G1       8        5        7 -2 LP7_LP6_LP2_AP3_AP2_AP1          C
4        C        4  S2017_G1       9        7        9 -2 LP7_LP6_LP2_AP7_AP3_AP1          C
5        C        5  S2017_G1      10        7        9 -2 LP3_LP2_LP1_AP3_AP2_AP1          C
6       NC        6  S2017_G2      18        7        6  1 LP3_LP2_LP1_AP3_AP2_AP1         NC
20 LastRow        7  S2017_G2      20       10        6  4 LP9_LP2_LP1_AP5_AP3_AP1         NC
```

A pesar de que ningún equipo ha anotado durante ese stint, asignas un más menos de -2.

De ahí que sea necesario primero crear una variable que te diga a qué stint pertenece cada línea de los datos jugada a jugada y luego calcular el más menos agrupando por stint.

Además será necesario calcular el tiempo transcurrido en cada stint. Esto no lo mencionamos en la última reunión pero es necesario. No queremos que un +/- de 0 en dos minutos sea lo mismo que un +/- de 0 en 25 minutos. De modo que necesitarás calcularlo.

**Comment by PaulaMorBla14** [comment]
Arreglado lo del PM, no me había dado cuenta. 

Lo de añadir la última fila lo hago porque como lo que hace es comparar con la siguiente, como no hay más después de la última, me añade un `NA` y por lo tanto, me elimina este stint. Ahora ya está arreglado para que aparezcan primero todos y luego para que no aparezcan duplicados con la información SUMADA (¿corrector no? sumamos minuts y el PM).

Minutos también añadidos en mi base de datos de juguete.

**Comment by solmos** [comment]
Puede ser útil si asocias commits que estén relacionados con un Issue. Si en el mensaje del commit incluyes el número del issue con #xx (donde xx es el número del Issue), aparecerá un link al ese commit específico en el hilo y será más fácil saber qué hiciste para cerrar el issue.

Yo suelo poner algo como "Related to #xx". También puedes cerrar el issue automáticamente con el commit usando la palabras clave "Fixes #xx"  o "Solves #xx".
