### ISSUE TITLE
Tenemos en cuenta informació partido o no?

### ISSUE THREAD

**Issue by PaulaMorBla14** [PaulaMorBla14/TFG-Baloncesto#14]
Una duda, es necesario mostrar la `SeasonGame` y el `Quarter`??

En `df_dummys_PM` tengo los stints únicos por `Quarter `y `SeasonGame`. Pero los stints se repiten (por ejemplo, si al acabar un cuarto, el equipo que estaba en pista vuelve a salir sin cambios al siguiente).

En `df_dummys_PM_2` tengo los stints únicos sin tener en cuenta `Quarter `y `SeasonGame`, y por lo tanto son únicos en toda la temporada.

https://github.com/PaulaMorBla14/TFG-Baloncesto/blob/146304227e0f8b71113cbef1441adbb7f1f5660e/TOY_1.Rmd#L299-L312

Entonces no sé si necesito guardar esta información del partido o si queremos los stints únicos, independientemente del partido o del cuarto.

**Comment by solmos** [comment]
Sí, guarda cada stint por separado, no los agrupes por combinaciones de alineaciones únicas. Así luego puedes utilizar otras variables (el tiempo del stint o el cuarto del partido, por ejemplo).

Por otro lado, no entiendo por qué haces esto:

https://github.com/PaulaMorBla14/TFG-Baloncesto/blob/b0255a3cfd1acc6aacff764e39291b223699cf88/TOY_1.Rmd#L308

¿Por qué has creído necesario hacer esto?

Queremos que estas variables tengan valores -1, 0, 1 indicando si un jugador está en pista o no (y en casa o fuera). El más-menos ya lo tenemos como variable dependiente (outcome) para el modelo.

**Comment by PaulaMorBla14** [comment]
Esto lo hice para calcular también el Más/Menos clásico (es un añadido al trabajo) para poder comparar al final.
