### ISSUE TITLE
Problemas al cargar dos bases de datos .csv

### ISSUE THREAD

**Issue by PaulaMorBla14** [PaulaMorBla14/TFG-Baloncesto#17]
https://github.com/PaulaMorBla14/TFG-Baloncesto/blob/3a1fe87c4baaaa09e960f04fee07a9af80b0024f/TFG_MetodosEstadisticosBaloncesto.Rnw#L367-L368

No sé qué ocurre con estos datos. Tienen el mismo formato que todos los demás, pero no me deja cargarlos. Me aparece el siguiente error: 

```
Rows: 8038 Columns: 359                                                                                                              
Error in nchar(x, "width") : invalid multibyte string, element 1
```

No sé qué es lo que está pasando porque solo cambio la base de datos original, todo lo demás es exactamente el mismo proceso para datos los .csv

**Comment by solmos** [comment]
Parece que tiene que ver con algunos caracteres en algunas de las variables de estos CSVs que tu sistema operativo no reconoce. He escuchado que R en Windows suele tener problemas de este tipo.

Entiendo que estos CSVs los generas tú, ¿verdad? Prueba a guardarlos en formato .rds en lugar de .csv con la función `saveRDS()`. De hecho, te recomiendo que los objetos que vayas generando y quieras guardar, los guardes en formato RDS.

**Comment by PaulaMorBla14** [comment]
Solucionado!
