### ISSUE TITLE
Nombres de los jugadores cambian según temporada

### ISSUE THREAD

**Issue by PaulaMorBla14** [PaulaMorBla14/TFG-Baloncesto#19]
https://github.com/PaulaMorBla14/TFG-Baloncesto/blob/3a1fe87c4baaaa09e960f04fee07a9af80b0024f/TFG_MetodosEstadisticosBaloncesto.Rnw#L387-L392

Hay nombres de jugadores que cambian (añaden un "JR." o nombres que se corrigen porque estaban mal escritos... 

Ejemplos: 
**Acik, Tutku** cambia a **Açik, Tutku**
**Agravanis, Dimitrios** cambia a **Agravanis, Dimitris**

Entre otros casos.

¿Qué hago?

**Comment by solmos** [comment]
Me lo temía. Esto puede ser algo complicado de resolver.

Quizás podrías hacer algo con las distancias entre strings. R tiene una función para esto.

```r
x <- c("Jordan, Micheal", "Acik, Tutku", "Rodriguez, Sergio")
y <- c("Jordan, Micheal", "Açik, Tutku", "Agravanis, Dimitris")

dist_matrix <- adist(x, y)
diag(dist_matrix)
```
```
[1]  0  1 16
```

Con esto puedes identificar los nombres que cambian ligeramente (distancia < 3, por ejemplo). Y luego decidir qué hacer con estos, si homogeneizarlos, o eliminar las filas en los que estos aparezcan. Yo supongo que no habrán muchos casos.

Si haces algo con `adist()`, podrías añadirlo al trabajo hablando del método que utiliza. Mira `?adist` para más detalles.

**Comment by PaulaMorBla14** [comment]
He creado manualmente un data frame con todos aquellos nombres que aparecen mal en la primera columna y luego en la segunda de forma correcta. Como puedo hacer para que me sustituya el malo por el bueno??

**Comment by PaulaMorBla14** [comment]
En esta linia está el data.frame que comentaba:

https://github.com/PaulaMorBla14/TFG-Baloncesto/blob/9f86d010b14c2c251e5dafad4a37e119f524de77/TFG_MetodosEstadisticosBaloncesto.Rnw#L397-L398

**Comment by solmos** [comment]
Yo lo haría uniendo `players_with_errors` a tu data frame con todos los jugadores y luego sustituir los valores de la variable de los nombres que tengan un match.

Un ejemplo:

```r
library(dplyr)

players_with_errors <- data.frame(
  wrong = c("Janito James", "Pepto Jordan"),
  right = c("Juanito James", "Pepito Jordan")
)

pbp <- data.frame(
  game = rep(1, 10),
  player = rep(
    c("Sergio Rodriguez", players_with_errors$wrong),
    length.out = 10
  ),
  play_type = sample(c("FG2M", "FG3M"), 10, replace = TRUE)
)

pbp |>
  left_join(name_conversion_df, by = c(player = "wrong")) |>
  mutate(player = ifelse(!is.na(right), right, player))
```
```
   game           player play_type         right
1     1 Sergio Rodriguez      FG2M          <NA>
2     1    Juanito James      FG2M Juanito James
3     1    Pepito Jordan      FG2M Pepito Jordan
4     1 Sergio Rodriguez      FG3M          <NA>
5     1    Juanito James      FG2M Juanito James
6     1    Pepito Jordan      FG3M Pepito Jordan
7     1 Sergio Rodriguez      FG3M          <NA>
8     1    Juanito James      FG2M Juanito James
9     1    Pepito Jordan      FG3M Pepito Jordan
10    1 Sergio Rodriguez      FG3M          <NA>
```
