### ISSUE TITLE
URL al html (pero no al código)

### ISSUE THREAD

**Issue by PaulaMorBla14** [PaulaMorBla14/TFG-Baloncesto#22]
https://github.com/PaulaMorBla14/TFG-Baloncesto/blob/9f86d010b14c2c251e5dafad4a37e119f524de77/TFG_MetodosEstadisticosBaloncesto.Rnw#L798

Quiero añadir aquí el HTML que me aparece cuando hagi knit, que se visualiza bien sin código de Rstudio. ¿Cómo puedo hacerlo?

**Comment by solmos** [comment]
No acabo de entender qué quieres hacer aquí. ¿Te refieres a que quieres que se vea el archivo html en GitHub tal como se ve al hacer knit y abririlo en RStudio o en un navegador web? Si es así, no es posible. GitHub no es un web server, no renderiza el código HTML.

¿Qué URL quieres añadir?

**Comment by PaulaMorBla14** [comment]
Sí quería hacer eso, porque es el más visual a mi modo de ver. Pues en todo caso lo pasaré a PDF y adjuntaré URL del PDF.
